#!/usr/bin/env python3
"""Scan languages/*/pack.json and regenerate everything that depends on the set of packs:
  - languages/index.json   (list of pack folders; the browser can't list directories itself)
  - data/embedded.js       (offline fallback for file:// use)
  - sw.js asset list + cache version (so installed copies pick up changes)
Run from anywhere:  python3 tools/build.py
"""
import hashlib, json, pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
concepts = json.loads((root / "data/concepts.json").read_text(encoding="utf-8"))
ids = [c["id"] for c in concepts]
errors, packs, order = [], {}, []

for folder in sorted((root / "languages").iterdir()):
    pf = folder / "pack.json"
    if not folder.is_dir() or not pf.exists():
        continue
    code = folder.name
    try:
        pack = json.loads(pf.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        errors.append(f"{code}: pack.json is not valid JSON ({e})"); continue
    if pack.get("language") != code:
        errors.append(f'{code}: "language" is {pack.get("language")!r} but the folder is named {code!r}')
    for key in ("name", "englishName", "voiceLocale"):
        if not pack.get(key): errors.append(f"{code}: missing {key!r}")
    tr = pack.get("translations", {})
    missing = [i for i in ids if not tr.get(i, {}).get("word")]
    extra = [i for i in tr if i not in ids]
    if missing: errors.append(f"{code}: missing words for {len(missing)} concepts, first: {missing[:5]}")
    if extra: errors.append(f"{code}: unknown concept IDs {extra[:5]}")
    audio = sorted(p.name for p in (folder / "audio").glob("*.mp3")) if (folder / "audio").is_dir() else []
    print(f"  {code:6} {pack.get('name','?'):12} words {len(ids)-len(missing)}/{len(ids)}   audio {len(audio)}/{len(ids)}")
    packs[code] = pack; order.append(code)
order.sort(key=lambda c: (packs[c].get("sortOrder", 100), c))

if errors:
    print("\nProblems found:"); [print(" -", e) for e in errors]; sys.exit(1)

(root / "languages/index.json").write_text(json.dumps(order, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
(root / "data/embedded.js").write_text("window.EMBEDDED_DATA = " + json.dumps({"concepts": concepts, "order": order, "packs": packs}, ensure_ascii=False) + ";\n", encoding="utf-8")

core = ["./", "./index.html", "./styles.css", "./app.js", "./manifest.webmanifest", "./data/concepts.json",
        "./data/embedded.js", "./languages/index.json", "./icons/icon.svg"]
core += [f"./{p.relative_to(root).as_posix()}" for p in sorted((root / "images").glob("*")) if p.suffix.lower() in (".jpg", ".jpeg", ".png")]
assets = core + [f"./languages/{c}/pack.json" for c in order]
assets += [f"./{p.relative_to(root).as_posix()}" for c in order for p in sorted((root / "languages" / c / "audio").glob("*.mp3"))]
version = hashlib.sha1(json.dumps(assets).encode() + b"".join((root / f).read_bytes() for f in ("app.js", "index.html", "styles.css"))
                       + (root / "data/concepts.json").read_bytes() + b"".join(json.dumps(p, sort_keys=True).encode() for p in packs.values())).hexdigest()[:8]
block = f'// BUILD:START (generated by tools/build.py — do not edit)\nconst CACHE = "language-book-{version}";\nconst ASSETS = {json.dumps(assets)};\n// BUILD:END'
sw = root / "sw.js"
sw.write_text(re.sub(r"// BUILD:START.*?// BUILD:END", lambda m: block, sw.read_text(encoding="utf-8"), flags=re.S), encoding="utf-8")
print(f"\nOK — languages: {', '.join(order)}  (cache {version})")
